"""Regression tests for the identity sent to RetroAchievements."""

from __future__ import annotations

import ctypes as C
import re
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

DAEMON_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(DAEMON_DIR))

from achievementbox.rcbridge import (  # noqa: E402
    RcApiRequest,
    RcClient,
    SERVER_CALLBACK,
)
from achievementbox.offline_queue import OfflineSubmissionQueue  # noqa: E402
from achievementbox.version import USER_AGENT, VERSION  # noqa: E402


class _Response:
    status = 200

    def __enter__(self):
        return self

    def __exit__(self, *_exc):
        return False

    def read(self):
        return b'{"Success":true}'


class RetroAchievementsIdentityTest(unittest.TestCase):
    def test_every_rc_client_request_uses_release_identity(self):
        """Capture representative rc_client calls at the HTTP boundary.

        All authenticated RA traffic generated by rcheevos enters Python
        through this one server callback, irrespective of the API operation.
        Exercising several operations guards both GET-like and POST requests.
        """
        client = RcClient.__new__(RcClient)
        client._log = self.fail
        client.response_log = None
        captured = []
        callback_statuses = []

        def capture(request, timeout):
            captured.append(request)
            self.assertEqual(timeout, 20)
            return _Response()

        @SERVER_CALLBACK
        def completed(response, _callback_data):
            callback_statuses.append(response.contents.http_status_code)

        calls = (
            (b"https://retroachievements.org/dorequest.php?r=login2",
             b"u=test&p=redacted"),
            (b"https://retroachievements.org/dorequest.php?r=patch",
             b"u=test&t=redacted&g=1"),
            (b"https://retroachievements.org/dorequest.php?r=awardachievement",
             b"u=test&t=redacted&a=1"),
        )

        with tempfile.TemporaryDirectory() as temp_dir:
            client._submission_queue = OfflineSubmissionQueue(Path(temp_dir))
            client._startup_queue_ids = set()
            with patch("achievementbox.rcbridge.urllib.request.urlopen",
                       side_effect=capture):
                for url, post_data in calls:
                    request = RcApiRequest(
                        url=url,
                        post_data=post_data,
                        content_type=b"application/x-www-form-urlencoded",
                    )
                    client._c_server_call(
                        C.pointer(request), completed, None, None)

        self.assertEqual(len(captured), len(calls))
        self.assertEqual(callback_statuses, [200] * len(calls))
        self.assertEqual(USER_AGENT, f"AchievementBox/{VERSION}")
        self.assertRegex(USER_AGENT, r"^AchievementBox/\d+\.\d+\.\d+$")
        for request in captured:
            headers = {name.casefold(): value
                       for name, value in request.header_items()}
            self.assertEqual(headers.get("user-agent"), USER_AGENT)


if __name__ == "__main__":
    unittest.main()
