#!/usr/bin/env python3
"""Assemble the buildable fpga/ tree from krikzz's upstream sources.

The public repository ships Achievement Box's original gateware
(wram_sniffer.sv, pad_watch.sv, frame_watch.sv), a patch with our
modifications, and the
prebuilt core; krikzz's Mega EverDrive dev sources stay in their upstream
repository, pinned here as a submodule. This script produces the complete
Quartus source tree locally:

  1. copies the required upstream files from the pinned
     references/mega-ed-pub submodule into fpga/ (same relative layout,
     so mega-pro.qsf's relative source paths keep working), then
  2. applies fpga/patches/achievement-box.patch with `git apply`.

Run from anywhere:

    git submodule update --init
    python fpga/assemble.py

The assembled upstream files are listed in fpga/.gitignore -- they are
krikzz's code and must not be committed to this repository.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

FPGA_DIR = Path(__file__).resolve().parent
ROOT = FPGA_DIR.parent
DEFAULT_PATCH = FPGA_DIR / "patches" / "achievement-box.patch"
DEFAULT_UPSTREAM = ROOT / "references" / "mega-ed-pub" / "fpga"

# Upstream files used verbatim by the shipped Mega Drive mapper build.
# Paths are relative both to <upstream>/ and to fpga/. Keep this aligned
# with fpga/fpga_pro/map_smd/mega-pro.qsf.
UNMODIFIED_FILES = (
    "fpga_pro/clocks.sdc",
    "fpga_pro/hwc.sv",
    "fpga_pro/top.sv",
    "fpga_pro/map_smd/mega-pro.qpf",
    "fpga_pro/map_smd/topcfg.sv",
    "mapper/lib_base/audio_out.sv",
    "mapper/lib_base/base_io.sv",
    "mapper/lib_base/defs.sv",
    "mapper/lib_base/dma.sv",
    "mapper/lib_base/map_nom.sv",
    "mapper/lib_base/map_sys.sv",
    "mapper/lib_base/mdp.sv",
    "mapper/lib_base/pi.sv",
    "mapper/lib_base/pi_map.sv",
    "mapper/lib_base/structs.sv",
    "mapper/lib_base/sys_cfg.sv",
    "mapper/lib_base/var.sv",
    "mapper/lib_bram/eep_24x.sv",
    "mapper/lib_bram/ram_cart.sv",
    "mapper/lib_bram/srm_smd.sv",
    "mapper/map_smd/map_cdb.sv",
)

# Upstream files that carry Achievement Box modifications: copied from the
# submodule, then patched. The patch is generated by publish.py from the
# development tree, so it can never drift from the sources that built the
# shipped .rbf.
PATCHED_FILES = (
    "fpga_pro/map_smd/mega-pro.qsf",
    "mapper/lib_base/everdrive.sv",
    "mapper/map_smd/hub.sv",
    "mapper/map_smd/map_smd.sv",
)

ASSEMBLED_FILES = UNMODIFIED_FILES + PATCHED_FILES


def assemble(out_fpga: Path, upstream: Path, patch: Path) -> None:
    """Copy the upstream closure into out_fpga and apply the patch."""
    if not upstream.is_dir():
        sys.exit(
            f"upstream sources not found at {upstream}\n"
            "initialise the pinned submodule first:\n"
            "    git submodule update --init"
        )
    if not patch.is_file():
        sys.exit(
            f"patch file not found at {patch}\n"
            "this script assembles the *published* tree; the development "
            "repository already contains the full fpga/ sources"
        )

    missing = [f for f in ASSEMBLED_FILES if not (upstream / f).is_file()]
    if missing:
        listing = "\n  ".join(missing)
        sys.exit(f"upstream tree is missing expected files:\n  {listing}")

    for f in ASSEMBLED_FILES:
        dest = out_fpga / f
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(upstream / f, dest)

    # The patch uses a/fpga/... b/fpga/... paths, so apply from out_fpga's
    # parent. core.autocrlf is forced off so the patched files keep the exact
    # bytes of the sources that built the shipped .rbf, regardless of the
    # user's git line-ending configuration.
    result = subprocess.run(
        ["git", "-c", "core.autocrlf=false", "apply",
         "--whitespace=nowarn", str(patch)],
        cwd=out_fpga.parent,
    )
    if result.returncode:
        sys.exit(
            "git apply failed -- the patch does not match the pinned "
            "upstream sources (is the submodule at the pinned commit?)"
        )

    print(f"Assembled {len(ASSEMBLED_FILES)} upstream files into {out_fpga}")
    print(f"Applied {patch.name} ({len(PATCHED_FILES)} files modified)")
    print("Build with Quartus Prime Lite 20.1.1: open "
          "fpga/fpga_pro/map_smd/mega-pro.qpf -- see fpga/README.md")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--out", type=Path, default=FPGA_DIR, metavar="DIR",
        help="fpga/ directory to assemble into (default: alongside this "
             "script; the patch expects DIR to be named fpga)")
    parser.add_argument(
        "--upstream", type=Path, default=DEFAULT_UPSTREAM, metavar="DIR",
        help="upstream fpga/ source tree (default: the pinned "
             "references/mega-ed-pub submodule)")
    parser.add_argument(
        "--patch", type=Path, default=DEFAULT_PATCH, metavar="FILE",
        help="Achievement Box modifications patch (default: "
             "fpga/patches/achievement-box.patch)")
    args = parser.parse_args()

    out_fpga = args.out.resolve()
    if out_fpga.name != "fpga":
        sys.exit(f"--out must point at a directory named fpga, got {out_fpga}")
    assemble(out_fpga, args.upstream.resolve(), args.patch.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
